### PR TITLE
make sure that period is not larger than size of input series

### PR DESCRIPTION
**Pull request by boegel**
fix for `NaN` issue reported in #4

### CODE REVIEW

**Comment by jrmontag** [comment]
Thanks for the issue and PR, @boegel. I'll have a look at it as soon as I can.

**Comment by tejaslodaya** [comment]
Hi @jrmontag , 
Please merge the above PR. It seems valid and is a bug in the case where the number of periods is greater than the number of observed values.

It'll help people who're further looking at it.

CC: @boegel

**Comment by jrmontag** [comment]
Thanks for the bump, @tejaslodaya.

**Comment by darkblackside** [comment]
Is it possible to publish your fix to pip?
I had the same problem and searched a while until I found the error. I've installed 0.0.3 from pip and there the bugfix is not included.

**Pull request merged**
